# Generated by Django 4.2.4 on 2023-08-22 19:08

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=builtins.dir)),
                ('txt_file', models.FileField(blank=True, null=True, upload_to='txts')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='voices')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=builtins.dir)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.post')),
            ],
        ),
    ]
