# Generated by Django 4.2.4 on 2023-08-25 08:53

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_image_alter_post_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[home.models.validate_phone_number]),
        ),
    ]
